{% set name = "beta9" %}
{% set version = "0.1.151" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beta9-{{ version }}.tar.gz
  sha256: 2546caa4f0271bee76421b5de14ea52351b405097c7680961b2e9f7386b43fc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8,<4.0
    - typeguard <3.0.0,>=2.13.3
    - typing-extensions <5.0.0,>=4.7.1
    - grpclib <0.5.0,>=0.4.7
    - grpcio ==1.69.0
    - asgiref <4.0.0,>=3.8.1
    - cloudpickle <4.0.0,>=3.0.0
    - rich <14.0.0,>=13.9.4
    - click <9.0.0,>=8.1.7
    - protobuf <5.0.0,>=4.25.1
    - fastapi <0.111.0,>=0.110.2
    - uvicorn <0.30.0,>=0.29.0
    - watchdog <5.0.0,>=4.0.0
    - betterproto-beta9 ==2.0.0b7
    - croniter <4.0.0,>=3.0.3
    - websocket-client <2.0.0,>=1.8.0
    - prompt-toolkit <4.0.0,>=3.0.48
    - requests <3.0.0,>=2.32.3
    - paramiko <4.0.0,>=3.5.0

test:
  imports:
    - beta9
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/beta9/
  summary: ''
  license: MPL-2.0
  license_file: src/beta9/vendor/pathspec/LICENSE

extra:
  recipe-maintainers:
    - asford
