{% set name = "minio-server" %}
{% set tag = "RELEASE.2020-12-18T03-27-42Z" %}
{% set version = tag.split(".")[1].split("T")[0].replace("-",".") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  binary_relocation: "False"
  number: 0
  script:
    - mkdir -p $PREFIX/bin
    - curl -JL -o $PREFIX/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio.{{ tag }} # [linux and x86_64]
    - curl -JL -o $PREFIX/bin/minio https://dl.minio.io/server/minio/release/darwin-amd64/minio.{{ tag }} # [osx and x86_64]
    - chmod +x $PREFIX/bin/minio

requirements:
  build:
    - curl

test:
  commands:
    - minio --help

about:
  home: https://github.com/minio/minio
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: |
    MinIO is a High Performance Object Storage released under Apache License
    v2.0. It is API compatible with Amazon S3 cloud storage service. Use MinIO
    to build high performance infrastructure for machine learning, analytics
    and application data workloads.
  doc_url: https://docs.min.io
  dev_url: https://github.com/minio/minio

extra:
  recipe-maintainers:
    - asford
