{% set name = "aws-ssm-tools" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-ssm-tools-{{ version }}.tar.gz
  sha256: a5185ee9c2e46895d0c8e9e35b294871214f63eab3387ca2dabe477f4c6b280f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pexpect
    - packaging
    - botocore
    - boto3

test:
  imports:
    - aws_ssm_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mludvig/aws-ssm-tools
  summary: 'Tools for AWS Systems Manager: ssm-session ecs-session ssm-ssh ssm-tunnel'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
