{% set name = "datargs" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datargs-{{ version }}.tar.gz
  sha256: a0195c32533aa84051cebc519e25fce41bcba6fd0640ae00aa77f87594109039

build:
  number: 0
  noarch: True
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - boltons >=20.2.1,<21.0.0
    - python >=3.7
    - typing-extensions >=3.10.0,<4.0.0

test:
  imports:
    - datargs
    - datargs.compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roee30/datargs
  summary: Declarative, type-safe command line argument parsers from dataclasses and attrs classes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
