{% set name = "sqlalchemy2-stubs" %}
{% set version = "0.0.2a24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy2-stubs-{{ version }}.tar.gz
  sha256: e15c45302eafe196ed516f979ef017135fd619d2c62d02de9a5c5f2e59a600c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing-extensions >=3.7.4

test:
  imports:
    - sqlalchemy-stubs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.sqlalchemy.org
  summary: Typing Stubs for SQLAlchemy 1.4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
