{% set name = "mergedeep" %}
{% set version = "1.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mergedeep-{{ version }}.tar.gz
  sha256: 0096d52e9dad9939c3d975a774666af186eda617e6ca84df4c94dec30004f2a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - mergedeep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/clarketm/mergedeep
  summary: A deep merge function for 🐍.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
