{% set name = "chai_lab" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chai_lab-{{ version }}.tar.gz
  sha256: 95d2eb5020aaf61686cae9b8a52af01679df75b97f5c407b35fa4d585e549797

build:
  entry_points:
    - chai = chai_lab.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling >=1.20
    - hatch-requirements-txt
    - pip
  run:
    - python >=3.10
    - antipickle ==0.2.0
    - beartype >=0.18
    - biopython >=1.83
    - einops >=0.8,<1.dev0
    - gemmi >=0.6.3,<0.7.dev0
    - ipykernel >=6.27,<7.dev0
    - jaxtyping >=0.2.25
    - matplotlib-base
    - modelcif >=1.0
    - mypy
    - numba >=0.59
    - numpy >=1.21,<2.dev0
    - pandas-stubs
    - pandas >=2.1,<3.dev0
    - pandera
    - pre-commit
    - pytest
    - rdkit ==2023.9.5
    - ruff ==0.6.3
    - tmtools >=0.0.3
    - pytorch >=2.3.1,<2.4.dev0
    - tqdm >=4.66,<5.dev0
    - transformers >=4.44,<5.dev0
    - typer >=0.12,<1.dev0
    - types-pyyaml
    - types-requests
    - types-tqdm
    - typing_extensions

test:
  imports:
    - chai_lab
  commands:
    - pip check
    - chai --help
  requires:
    - pip

about:
  summary: Chai Discovery tools for AI + protein research.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
