{% set name = "pytorch_scatter" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rusty1s/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f

build:
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cudatoolkit =10.0
    - cudatoolkit-dev =10.0
    - pytorch >=1.1
  run:
    - python
    - cudatoolkit =10.0
    - pytorch >=1.1

test:
  imports:
    - torch_scatter

about:
  home: https://github.com/rusty1s/pytorch_scatter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'PyTorch Extension Library of Optimized Scatter Operations'
  description: |
    This package consists of a small extension library of highly optimized
    sparse update (scatter) operations for the use in PyTorch, which are
    missing in the main package. Scatter operations can be roughly described as
    reduce operations based on a given "group-index" tensor. All included
    operations are broadcastable, work on varying data types, and are
    implemented both for CPU and GPU with corresponding backward
    implementations.
  doc_url: https://pytorch-scatter.readthedocs.io/
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - asford
