{% set name = "nested_lookup" %}
{% set version = "0.2.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nested-lookup-{{ version }}.tar.gz
  sha256: e39adacd11e879dd6383b0a832cde97edce25d2a29cbc03a9c80fefa3a131e8b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - nested_lookup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/russellballestrini/nested-lookup
  summary: Python functions for working with deeply nested documents (lists and dicts)
  license: SAX-PD
  license_file: CONTRIBUTING.rst

extra:
  recipe-maintainers:
    - asford
