{% set name = "nested_lookup" %}
{% set version = "0.2.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nested-lookup-{{ version }}.tar.gz
  sha256: 7b8900c8e706e4f8c3309ebde229b109f487b15b9a8cae27b99026ad11e4b64c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - nested_lookup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/russellballestrini/nested-lookup
  summary: Python functions for working with deeply nested documents (lists and dicts)
  license: SAX-PD
  license_file: CONTRIBUTING.rst

extra:
  recipe-maintainers:
    - asford
