{% set name = "betterproto-beta9" %}
{% set version = "2.0.0b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/betterproto_beta9-{{ version }}.tar.gz
  sha256: 122e0f6fbf9591e782848f3d486f1eb90657e215cb8aca74886d4ba6b8fa4b9a

build:
  skip: true  # [py>=400 or py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - grpclib <0.5.0,>=0.4.1
    - importlib-metadata >=1.6.0  # [py<38]
    - python-dateutil <3.0,>=2.8
    - typing-extensions <5.0.0,>=4.7.1

test:
  imports:
    - betterproto_beta9
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/beam-cloud/python-betterproto
  summary: A better Protobuf / gRPC generator & library
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
