{% set name = "beam-client" %}
{% set version = "0.2.126" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beam_client-{{ version }}.tar.gz
  sha256: d468d66453c91ffe3971a820e623d4985958c2f7e84c006acb61f9f1dd53ac85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8,<4.0
    - beta9 ==0.1.142
    - requests <3.0.0,>=2.31.0
    - websockets <13.0,>=12.0

test:
  imports:
    - beam_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/beam-client/
  summary: ''
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - asford
